"""Pydantic request/response schemas.

These models are the first line of defence: FastAPI uses them to validate
and coerce every incoming request *before* any business logic runs. Invalid
payloads are rejected with a clear, structured 422 response automatically.
"""

from __future__ import annotations

from typing import Optional

from pydantic import BaseModel, ConfigDict, Field, field_validator

from . import config


# ==========================================================================
# Requests
# ==========================================================================
class TransactionRequest(BaseModel):
    """Body for ``POST /transaction``.

    ``transactionId`` is an optional client-supplied idempotency key. If the
    client supplies a stable id and retries the request (e.g. after a network
    timeout), the server processes the transaction exactly once. If it is
    omitted, the server generates one — but the caller then loses dedup
    guarantees, so supplying it is strongly recommended for real clients.
    """

    model_config = ConfigDict(extra="forbid")  # reject unexpected fields

    userId: str = Field(
        ...,
        description="Identifier of the user the transaction belongs to.",
        examples=["alice"],
    )
    amount: float = Field(
        ...,
        gt=0,
        description="Positive value generated by this transaction.",
        examples=[125.50],
    )
    type: str = Field(
        default=config.DEFAULT_TRANSACTION_TYPE,
        description="Category of activity.",
        examples=["purchase"],
    )
    transactionId: Optional[str] = Field(
        default=None,
        description="Optional idempotency key (stable across retries).",
        examples=["3f9c1c2e-9b1a-4f2e-8c1a-2b3c4d5e6f70"],
    )

    @field_validator("userId")
    @classmethod
    def _validate_user_id(cls, value: str) -> str:
        import re

        value = value.strip()
        if not re.fullmatch(config.USER_ID_PATTERN, value):
            raise ValueError(
                "userId must be 1-64 chars of letters, digits, '_', '.' or '-'"
            )
        return value

    @field_validator("amount")
    @classmethod
    def _validate_amount(cls, value: float) -> float:
        # Reject NaN / Infinity which slip past simple > 0 checks.
        import math

        if not math.isfinite(value):
            raise ValueError("amount must be a finite number")
        if value < config.MIN_TRANSACTION_AMOUNT:
            raise ValueError(
                f"amount must be >= {config.MIN_TRANSACTION_AMOUNT}"
            )
        if value > config.MAX_TRANSACTION_AMOUNT:
            raise ValueError(
                f"amount must be <= {config.MAX_TRANSACTION_AMOUNT}"
            )
        # Money-like rounding to 2 decimal places keeps aggregates exact-ish
        # and prevents float-dust abuse (e.g. 0.000001 spam).
        return round(value, 2)

    @field_validator("type")
    @classmethod
    def _validate_type(cls, value: str) -> str:
        value = value.strip().lower()
        if value not in config.ALLOWED_TRANSACTION_TYPES:
            allowed = ", ".join(config.ALLOWED_TRANSACTION_TYPES)
            raise ValueError(f"type must be one of: {allowed}")
        return value

    @field_validator("transactionId")
    @classmethod
    def _validate_tx_id(cls, value: Optional[str]) -> Optional[str]:
        if value is None:
            return None
        value = value.strip()
        if not (1 <= len(value) <= 128):
            raise ValueError("transactionId must be 1-128 characters")
        return value


# ==========================================================================
# Responses
# ==========================================================================
class TransactionResponse(BaseModel):
    """Result of ``POST /transaction``."""

    status: str = Field(description="'created' or 'duplicate'.")
    duplicate: bool = Field(
        description="True if this was an idempotent replay of a prior request."
    )
    transactionId: str
    userId: str
    amount: float
    type: str
    processedAt: str = Field(description="ISO-8601 server timestamp.")
    user: "UserSummary" = Field(description="The user's state after processing.")
    message: str


class TransactionRecord(BaseModel):
    transactionId: str
    amount: float
    type: str
    timestamp: str


class UserSummary(BaseModel):
    """Body for ``GET /summary/:userId`` and embedded in other responses."""

    userId: str
    totalValue: float
    transactionCount: int
    averageTransaction: float
    firstSeen: str
    lastActivity: str
    transactions: list[TransactionRecord] = Field(
        default_factory=list,
        description="Most recent transactions (newest first), capped for size.",
    )


class RankingEntry(BaseModel):
    rank: int
    userId: str
    score: float = Field(description="Final blended score in [0, 1].")
    totalValue: float
    transactionCount: int
    lastActivity: str
    breakdown: "ScoreBreakdown"


class ScoreBreakdown(BaseModel):
    """Per-factor contribution to the final score (all weighted, in [0, 1])."""

    volume: float
    frequency: float
    recency: float


class RankingResponse(BaseModel):
    generatedAt: str
    userCount: int
    weights: dict[str, float]
    ranking: list[RankingEntry]


class HealthResponse(BaseModel):
    status: str
    version: str
    users: int
    transactions: int


class ErrorBody(BaseModel):
    code: str
    message: str
    details: Optional[object] = None


class ErrorResponse(BaseModel):
    error: ErrorBody


# Resolve forward references between the models above.
TransactionResponse.model_rebuild()
RankingEntry.model_rebuild()
